name: Discord PR Notification
on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@v1.3.1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          args: |
            {
              "embeds": [
                {
                  "title": "Новый PR: ${{ github.event.pull_request.title }}",
                  "description": "**Автор**: ${{ github.event.pull_request.user.login }}\n**Описание**: ${{ github.event.pull_request.body || 'Нет описания' }}",
                  "url": "${{ github.event.pull_request.html_url }}",
                  "color": 5814783
                }
              ]
            }
